RunMetadata:
  Memory: 256
  Networking: true
  ExposedPort: 8080
  PublicPort: 8080

TestingType: curl
ListOfCommands:
  - curl -I http://localhost:8080/status/418
  - http http://localhost:8080/get?foo=bar

ExpectedOutput:
  - HTTP/1.1 418 I'm a teapot
  - HTTP/1.1 200 OK
  - Access-Control-Allow-Credentials: true
  - Content-Type: application/json; charset=utf-8
  - PONG